prSections:
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: My Pull Requests
    filters: is:open author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
defaults:
  preview:
    open: true
    width: 70
  prsLimit: 20
  issuesLimit: 20
  view: prs
keybindings:
  prs: []
repoPaths: {}
pager:
  diff: delta
