; https://huggingface.co/blog/ggml-org/model-management-in-llamacpp

[unsloth/Qwen3.5-35B-A3B-GGUF:UD-Q4_K_XL:thinking]
hf-repo = unsloth/Qwen3.5-35B-A3B-GGUF:UD-Q4_K_XL
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
flash-attn = on
ctk = q8_0
ctv = q8_0
batch-size = 2048
ubatch-size = 512

[unsloth/Qwen3.5-35B-A3B-GGUF:UD-Q4_K_XL]
hf-repo = unsloth/Qwen3.5-35B-A3B-GGUF:UD-Q4_K_XL
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
flash-attn = on
ctk = q8_0
ctv = q8_0
batch-size = 2048
ubatch-size = 512
reasoning-budget = 0
