; https://huggingface.co/blog/ggml-org/model-management-in-llamacpp

[Qwen3.6-35B-A3B]
hf-repo = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_XL
ctx-size = 131072
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
flash-attn = on
ctk = q8_0
ctv = q8_0
batch-size = 2048
ubatch-size = 512

[Qwen3-Coder-Next]
hf-repo = unsloth/Qwen3-Coder-Next-GGUF:Q4_K_M
ctx-size = 131072
temp = 0.7
top-p = 0.8
top-k = 20
min-p = 0.00
batch-size = 2048
ubatch-size = 512

[gemma-4-26B-A4B]
hf-repo = google/gemma-4-26B-A4B-it-qat-q4_0-gguf:Q4_0
; hf-repo-draft = AtomicChat/gemma-4-26B-A4B-it-assistant-GGUF:F16
; spec-type = draft-mtp
; spec-draft-n-max = 4
; parallel = 1

ctx-size = 131072
temp = 1.0
top-p = 0.95
top-k = 64
