; https://huggingface.co/blog/ggml-org/model-management-in-llamacpp

[unsloth/gpt-oss-20b-GGUF:Q4_K_M]
hf-repo = unsloth/gpt-oss-20b-GGUF:Q4_K_M
ctx-size = 131072
temp = 1
top-p = 1.0
top-k = 0.00
batch-size = 2048
ubatch-size = 512

[unsloth/gpt-oss-120b-GGUF:Q4_K_M]
hf-repo = unsloth/gpt-oss-120b-GGUF:Q4_K_M
ctx-size = 131072
temp = 1
top-p = 1.0
top-k = 0.00
batch-size = 2048
ubatch-size = 512

[unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q4_K_M]
hf-repo = unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q4_K_M
ctx-size = 131072
temp = 0.7
top-p = 0.8
top-k = 20
min-p = 0.00
batch-size = 2048
ubatch-size = 512

[unsloth/Qwen3.6-35B-A3B-GGUF:UD-Q4_K_XL]
hf-repo = unsloth/Qwen3.6-35B-A3B-GGUF:UD-Q4_K_XL
ctx-size = 131072
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
flash-attn = on
ctk = q8_0
ctv = q8_0
batch-size = 2048
ubatch-size = 512

[unsloth/Qwen3-Coder-Next-GGUF:Q4_K_M]
hf-repo = unsloth/Qwen3-Coder-Next-GGUF:Q4_K_M
ctx-size = 131072
temp = 0.7
top-p = 0.8
top-k = 20
min-p = 0.00
batch-size = 2048
ubatch-size = 512

[LiquidAI/LFM2-24B-A2B-GGUF:Q4_K_M]
hf-repo = LiquidAI/LFM2-24B-A2B-GGUF:Q4_K_M
ctx-size = 131072
temp = 0.1
top-p = 0.95
top-k = 50
repeat-penalty = 1.05
flash-attn = on

[unsloth/gemma-4-26B-A4B-it-GGUF]
hf-repo = unsloth/gemma-4-26B-A4B-it-GGUF
ctx-size = 131072
temp = 1.0
top-p = 0.95
top-k = 64
